project:
  type: website
  output-dir: _site

website:
  title: "India's Tiger Network"
  navbar:
    left:
      - href: index.qmd
        text: Story
      - href: growth.qmd
        text: Growth
      - href: connectivity.qmd
        text: Connectivity
      - href: suitability.qmd
        text: Habitat
      - href: methods.qmd
        text: Methods
      - href: data.qmd
        text: Data & References

format:
  html:
    theme: cosmo
    page-layout: full
    toc: true

execute:
  freeze: auto
